apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-lts
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letencryp-prod
    kind: ClusterIssuer
  commonName: k8s.marcovergueira.com
  dnsNames:
    - k8s.marcovergueira.com
    - www.k8s.marcovergueira.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - k8s.marcovergueira.com
          - www.k8s.marcovergueira.com
